config/routes.rb
Rails.application.routes.draw do

  resources :milestones

  resources :categories
  
  resources :profiles do 
    member do 
      get :following, :followers
    end
  end 
  

  devise_for :users

  resources :goals

  root to: "goals#index"

  get "goals/new" => "goals#new", :as => :new

  resources :discussions

  resources :posts do
    resources :discussions
  end

  resources :projects do
    resources :posts
  end

  get "postindex", to: "project#postindex"
  

  get "portfolioindex", to: "profile#portfolioindex"

  resources :relationships, only: [:create, :destroy]

end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
  belongs_to :project
  has_many :goals
end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController
  before_action :set_milestone, only: [:show, :edit, :update, :destroy]
  before_action :check_user
  # GET /milestones
  # GET /milestones.json
  def index
    @milestones = Milestone.all
  end

  # GET /milestones/1
  # GET /milestones/1.json
  def show
  end

  # GET /milestones/new
  def new
    @milestone = Milestone.new
  end

  # GET /milestones/1/edit
  def edit
  end

  # POST /milestones
  # POST /milestones.json
  def create
    @milestone = Milestone.new(milestone_params)

    respond_to do |format|
      if @milestone.save
        format.html { redirect_to @milestone, notice: 'Milestone was successfully created.' }
        format.json { render :show, status: :created, location: @milestone }
      else
        format.html { render :new }
        format.json { render json: @milestone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /milestones/1
  # PATCH/PUT /milestones/1.json
  def update
    respond_to do |format|
      if @milestone.update(milestone_params)
        format.html { redirect_to @milestone, notice: 'Milestone was successfully updated.' }
        format.json { render :show, status: :ok, location: @milestone }
      else
        format.html { render :edit }
        format.json { render json: @milestone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /milestones/1
  # DELETE /milestones/1.json
  def destroy
    @milestone.destroy
    respond_to do |format|
      format.html { redirect_to milestones_url, notice: 'Milestone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_milestone
      @milestone = Milestone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def milestone_params
      params.require(:milestone).permit(:description, :project_id)
    end
end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/views/milestones/_form.html.erb
<%= simple_form_for(@milestone) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :description %>
    <%= f.association :project %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/milestones/edit.html.erb
<h1>Editing milestone</h1>

<%= render 'form' %>

<%= link_to 'Show', @milestone %> |
<%= link_to 'Back', milestones_path %>

app/views/milestones/index.html.erb
<h1>Listing milestones</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @milestones.each do |milestone| %>
      <tr>
        <td><%= milestone.description %></td>
        <td><%= milestone.project %></td>
        <td><%= link_to 'Show', milestone %></td>
        <td><%= link_to 'Edit', edit_milestone_path(milestone) %></td>
        <td><%= link_to 'Destroy', milestone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Milestone', new_milestone_path %>

app/views/milestones/new.html.erb
<h1>New milestone</h1>

<%= render 'form' %>

<%= link_to 'Back', milestones_path %>

app/views/milestones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @milestone.description %>
</p>

<p>
  <strong>Project:</strong>
  <%= @milestone.project %>
</p>

<%= link_to 'Edit', edit_milestone_path(@milestone) %> |
<%= link_to 'Back', milestones_path %>