config/routes.rb
Rails.application.routes.draw do

  resources :milestones

  resources :categories
  
  resources :profiles do 
    member do 
      get :following, :followers
    end
  end 
  

  devise_for :users

  resources :goals

  root to: "goals#index"

  get "goals/new" => "goals#new", :as => :new

  resources :discussions

  resources :posts do
    resources :discussions
  end

  resources :projects do
    resources :posts
  end

  get "postindex", to: "project#postindex"
  

  get "portfolioindex", to: "profile#portfolioindex"

  resources :relationships, only: [:create, :destroy]

end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  belongs_to :post
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :set_discussion, only: [:show, :edit, :update, :destroy]
  before_action :check_user
  # GET /discussions
  # GET /discussions.json
  def index
    @discussions = Discussion.all
  end

  # GET /discussions/1
  # GET /discussions/1.json
  def show
  end

  # GET /discussions/new
  def new
    @discussion = Discussion.new
  end

  # GET /discussions/1/edit
  def edit
    @post = Post.find(params[:post_id])
    
  end

  # POST /discussions
  # POST /discussions.json
  def create
    @discussion = Discussion.new(discussion_params)
    @post = @discussion.post
    @project = @post.project

    respond_to do |format|
      if @discussion.save
        format.html { redirect_to [@project, @post], notice: 'Discussion was successfully created.' }
        format.json { render :show, status: :created, location: @discussion }
      else
        format.html { render :new }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discussions/1
  # PATCH/PUT /discussions/1.json
  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        format.html { redirect_to @discussion, notice: 'Discussion was successfully updated.' }
        format.json { render :show, status: :ok, location: @discussion }
      else
        format.html { render :edit }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discussions/1
  # DELETE /discussions/1.json
  def destroy
   @post = @discussion.post
    @project = @post.project

    @discussion.destroy
    respond_to do |format|
      format.html { redirect_to [@project, @post], notice: 'Discussion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discussion
      @discussion = Discussion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discussion_params
      params.require(:discussion).permit(:post_id, :comment, :annotation)
    end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/discussions/_form.html.erb
<%= simple_form_for(@discussion) do |f| %>
  <%= f.error_notification %>

	<div class="form-inputs">
      
    <%= f.input :comment, label: 'Any thoughts?', placeholder: 'Tip: You can also draw' %>

    <%= f.hidden_field :annotation %>
  
    <%= f.hidden_field :post_id, value: @post.id %>

  </div>



<div class="form-actions">
	  <a href="#tools_sketch" data-tool="marker"><span class="btn btn-default fa fa-paint-brush fa-lg"></span></a>
  <a href="#tools_sketch" data-tool="eraser"><span class="btn btn-default fa fa-eraser fa-lg"></span></a>
		<%= f.submit (@discussion.new_record? ? "Submit" : "Change my Post"), class:'btn btn-default' %>
</div>


<% end %>

app/views/discussions/edit.html.erb
<h1>Editing discussion</h1>

<%= render 'form' %>

<%= link_to 'Show', @discussion %> |
<%= link_to 'Back', discussions_path %>

app/views/discussions/index.html.erb
<h1>Listing discussions</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @discussions.each do |discussion| %>
      <tr>
        <td><%= discussion.post %></td>
        <td><%= discussion.comment %></td>
        <td><%= link_to 'Show', discussion %></td>
        <td><%= link_to 'Edit', edit_discussion_path(discussion) %></td>
        <td><%= link_to 'Destroy', discussion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Discussion', new_discussion_path %>

app/views/discussions/new.html.erb
<h1>New discussion</h1>

<%= render 'form' %>

<%= link_to 'Back', discussions_path %>

app/views/discussions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @discussion.post %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @discussion.comment %>
</p>

<%= link_to 'Edit', edit_discussion_path(@discussion) %> |
<%= link_to 'Back', discussions_path %>