config/routes.rb
Rails.application.routes.draw do

  resources :milestones

  resources :categories
  
  resources :profiles do 
    member do 
      get :following, :followers
    end
  end 
  

  devise_for :users

  resources :goals

  root to: "goals#index"

  get "goals/new" => "goals#new", :as => :new

  resources :discussions

  resources :posts do
    resources :discussions
  end

  resources :projects do
    resources :posts
  end

  get "postindex", to: "project#postindex"
  

  get "portfolioindex", to: "profile#portfolioindex"

  resources :relationships, only: [:create, :destroy]

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :project
  after_create :order_post
  after_destroy :reorder_post
  
  # corvo - Validates presence of both text and post image
  validates :post_text, presence: true
  validates :post_img, presence: true

  # corvo - Relates Discussions to Posts and destroys dependencies upon deletion
  has_many :discussions, dependent: :destroy		

  # corvo - Added paperclip to Post ( for attaching files ), beneath, conditionals
  has_attached_file :post_img, :styles => { 
                        :s_150 => "150x150>",
  											:m_400 => "400x400>",
                        :m_600 => "600x600>",
                        :l_700 => "700x700>",
  											:l_800s => "800x800>",
                        :l_900 => "900x900>"} #,
  					# :url => "/assets/posts/:id/:style/:basename.:extension",
  					# :path => ":rails_root/:public/assets/posts/:id/:style/:basename.:extension"
            

  # corvo - validations in size and kind
  validates_attachment :post_img, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  validates_with AttachmentSizeValidator, :attributes => :post_img, :less_than => 1.megabytes


  def order_post
    self.order = Post.where(project_id: self.project.id).count 
    self.save
  end

  def assign_order(index)
    self.order = index + 1
    self.save
  end
  def reorder_post
    @posts = Post.where(project_id: self.project.id).where.not(order: self.order).order(order: :asc)
    @posts.each do |post|
      post.assign_order(@posts.index(post))
    end    
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :check_user

  
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
        @projects = current_user.projects
        @project = @post.project
    @discussion = Discussion.new
      
    @posts = current_user.posts
    @next_post = Post.where(project_id: @post.project.id, order: (@post.order + 1)).take
    @previous_post = Post.where(project_id: @post.project.id, order: (@post.order - 1)).take
    render :show, layout: "project" 
  end

  # GET /posts/new
  def new

    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @project = Project.find(params[:project_id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @project = @post.project

    respond_to do |format|
      if @post.save
        format.html { redirect_to @project, notice: 'Post was successfully created' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @project = @post.project

    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_path, notice: 'Post was successfully updated' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @project = @post.project
    
    @post.destroy
    respond_to do |format|
      format.html { redirect_to @project, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:post_text, :post_img, :project_id, :order)
    end
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/views/posts/_form.html.erb
<%= simple_form_for(@post, :html => { :multipart => true }) do |f| %>
  <%= f.error_notification %>


<div class="form-inputs">

    <%= f.input :post_text, label: 'Describe Your Post' %>

	<%= f.hidden_field :project_id, value: @project.id %>
 
	<%= f.file_field :post_img %>
  
  	<br>

    <%= f.submit @post.new_record? ? "Submit" : "Change Post", :class => 'btn btn-default' %>

</div>


<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>


<%= link_to 'Show', @post, :class => "btn btn-default" %>
<%= link_to 'Back', project_path(@post.project), :class => "btn btn-default" %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>Post text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.project %></td>
        <td><%= post.post_text %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', project_path(@post.project) %>

app/views/posts/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
 <div class="well block" id="wellspecial">
<div class="special" id="postcont">


	<div class="row-fluid">
		<!-- OUTSIDE WRAPPER -->

		<div class="col-sm-8 col-md-8" id="canvas_container">


			<!-- THIS IS THE LOOP THAT SHOWS THE ANNOTATIONS -->
			<div class="affix" style="z-index: 100;" id="invisibleaffix">
				<% @post.discussions.each do |u| %>
				<img src='<%= u.annotation %>' class='test hidden' id="<%= u.id %>" />
				<% end %>
			</div>

			<!-- THIS IS THE CANVAS USING SKETCH.JS THING -->
			<div class="affix">

				<canvas class="sketch_canvas" id="tools_sketch" style="background: url(<%= @post.post_img.url(:m_400)%>) no-repeat center"/>

					<script type="text/javascript">
					$(function() {
						$('#tools_sketch').sketch({defaultColor: "#ff0000", 
					});
						$('canvas').attr('height', ($(window).height()/1.7).toString() + 'px'); 
						$('canvas').attr('width', $('#canvas_container').width().toString() + 'px'); 
						$('#mysketch').sketch();		
						$('#tools_sketch').on('click', function(){
							console.log($('#tools_sketch')[0].toDataURL());
							var sk = $('#tools_sketch');
							$('#targetImage').attr('src', sk[0].toDataURL() );
							$('#discussion_annotation').val($('#tools_sketch')[0].toDataURL())
						});	    

					});
					$('#upload').click(function () {
						$.post('/upload.', { data: $('#targetImage').get(0).toDataURL() }, 
							function () { alert('uploaded'); });
					});	
					</script>

				</div>
			</div>

<div class="col-sm-3" id="comments_col">

				<!-- USER AVATAR GOES HERE -->

				<div id="post_text">	
					<strong><%= @post.post_text %>&nbsp;&nbsp;</strong><%= link_to content_tag(:i,nil, :class=>"fa fa-pencil-square-o fa-lg"), edit_project_post_path(@post.project, @post), :class => "btn btn-default" %><br><br>
					Post #<%= @post.order %> <% if @previous_post  %> 
					<%= link_to content_tag(:i,nil, :class=>"fa fa-arrow-left fa-md"), project_post_path(@post.project.id, @previous_post),:class => "btn btn-default" %>
                 <% end %>
                 
  				 <% if  @next_post   %>
  				 	<%= link_to content_tag(:i,nil, :class=>"fa fa-arrow-right fa-md"), project_post_path(@post.project.id, @next_post), :class => "btn btn-default"  %>
				 <% end %><br>
  				Created: <%= time_ago_in_words @post.created_at %> ago



				</div>


				<!-- <h3>New Discussion</h3> -->
				<%= render 'discussions/form' %>

				<!-- Show Discussions generated here -->
				<% @post.discussions.each do |u| %>

				<div class="commentdiv">
					<p><%= u.comment %>&nbsp;</p>
					<p><i><%= time_ago_in_words u.created_at %> ago</i></p>
					
					<div class="btn-group btn-toggle"> 
						<button class="btn btn-default" id="toggle_on_<%= u.id %>">ON</button>					
						<button class="btn btn-default" id="toggle_off_<%= u.id %>">OFF</button>
					</div>
						<%= link_to content_tag(:i,nil, :class=>"fa fa-trash-o fa-lg"), u, method: :delete, data: { confirm: 'Delete Discussion?' }, :class => "btn btn-default", :id=>"comment_delete" %>	
						<br>
						<br>				
					</div>


				<!-- Add jquery toggle magic stuff -->

				<script type="text/javascript">
				$(document).ready(function() {
					$("#toggle_on_<%= u.id %>").click(
						function(){
							$('.test').addClass('hidden');
							$('#<%= u.id %>').removeClass('hidden');
						}
						);

					$("#toggle_off_<%= u.id %>").click(
						function(){
							$('#<%= u.id %>').addClass('hidden');
						}
						);
				});   
				</script>

				<% end %>
			</div>
		</div>

	</div>